version: '3.6'
services:
  selenium-chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    container_name: ddev-${DDEV_SITENAME}-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "41343:5900"
