name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: vendor/bin/codecept run --steps

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: test-result
          path: tests/_output

  release:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release bluesprints
        uses: xedi/action-subtree-sync@1.0.0
        with:
          subtree: 'vertexvaar/bluesprints'
          subtree_deploy_key: ${{ secrets.DEPLOY_KEY_BLUESPRINTS }}
          split_prefix: 'packages/bluesprints'

      - name: Release bluefluid
        uses: xedi/action-subtree-sync@1.0.0
        with:
          subtree: 'vertexvaar/bluefluid'
          subtree_deploy_key: ${{ secrets.DEPLOY_KEY_BLUEFLUID }}
          split_prefix: 'packages/bluefluid'
